; This file was auto-generated by drush_make
core = 7.x
api = 2
projects[] = "drupal"

; Modules
projects[] = "admin"
projects[] = "ctools"
projects[] = "date"
projects[] = "devel"
projects[] = "features"
projects[] = "migrate"
projects[] = "views"

; Modules :: Preservation
projects[migrate_preservation][download][type] = "git"
projects[migrate_preservation][download][url] = "git://github.com/webgeeks/migrate_preservation.git"
projects[migrate_preservation][type] = "module"

; Themes
projects[] = "omega"
projects[] = "rubik"
projects[] = "tao"
