; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
projects[] = "admin"
projects[] = "ctools"
projects[] = "date"
projects[] = "devel"
projects[] = "features"
projects[] = "migrate"
projects[] = "views"
; Themes
projects[] = "omega"
projects[] = "rubik"
projects[] = "tao"
; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[migrate_preservation][download][type] = ""
projects[migrate_preservation][download][url] = ""
projects[migrate_preservation][type] = "module"

